version: '3'
services:
  sut:
    env_file:
      - .env
    build:
      context: .
      args:
        jdbc_driver_version: ${jdbc_driver_version}
    command: /opt/test_liquibase_postgres/run_test.sh
    depends_on:
      - db
    image: liquibase-postgres:build
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: liquibase
      POSTGRES_PASSWORD: liquibase
    ports:
      - 5432:5432
